//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaven.Application.Ingest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Etl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Etl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palaven.Application.Ingest.Resources.Etl", typeof(Etl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bronze stage. Document analysis is started using Azure AI Document Intelligence..
        /// </summary>
        internal static string BronzeStageStartDocumentAnalysis {
            get {
                return ResourceManager.GetString("BronzeStageStartDocumentAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEY DEL IMPUESTO SOBRE LA RENTA|Última Reforma DOF|ESTADOS UNIDOS MEXICANOS|CÁMARA DE DIPUTADOS DEL H. CONGRESO DE LA UNIÓN|Secretría General|Secretaría de Servicios Parlamentarios|UNIDOS|ESTADOS|NOS|Párrafo con fracciones|Párrafo adicionado|Párrafo reformado|ESTADO.
        /// </summary>
        internal static string TaxLawDocumentHeadingStrings {
            get {
                return ResourceManager.GetString("TaxLawDocumentHeadingStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo adicionado.
        /// </summary>
        internal static string TaxLawInvalidArticleIds {
            get {
                return ResourceManager.GetString("TaxLawInvalidArticleIds", resourceCulture);
            }
        }
    }
}
