//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaven.Infrastructure.Llm.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GemmaPromptTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GemmaPromptTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palaven.Infrastructure.Llm.Resources.GemmaPromptTemplates", typeof(GemmaPromptTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;start_of_turn&gt;user
        ///Answer the following question in a concise and informative manner following the next directions:
        ///1. The question is in spanish, then answer in spanish.
        ///2. Use one of the next articles to answer the given question. 
        ///3. The articles are delimited by the tags &lt;article&gt;&lt;/article&gt;. Each article is different. You can generate an answer using one or many of the articles but in the response you must mention what articles you used.
        ///
        ///{articles}
        ///
        ///Question: {instruction}&lt;end_of_turn&gt;
        ///&lt;start [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GemmaAugmentedQuery {
            get {
                return ResourceManager.GetString("GemmaAugmentedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;start_of_turn&gt;user
        ///Answer the following question in a concise and informative manner. The question is written in Spanish language, then answer in Spanish language.
        ///{instruction}&lt;end_of_turn&gt;
        ///&lt;start_of_turn&gt;model.
        /// </summary>
        internal static string GemmaSimpleQuery {
            get {
                return ResourceManager.GetString("GemmaSimpleQuery", resourceCulture);
            }
        }
    }
}
