//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Palaven.Ingest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChatGptPromptTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatGptPromptTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Palaven.Ingest.Resources.ChatGptPromptTemplates", typeof(ChatGptPromptTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an AI assistant. You must extract a text in a specific format with the following instructions:
        ///1. The text will be delimited by the tags &lt;working_text&gt;&lt;/working_text&gt;
        ///2. The text is in Spanish.
        ///3. You must generate a valid response in JSON with the following structure:
        ///{
        ///&apos;success&apos;: {true|false}
        ///&apos;article&apos;:{article_identifier},
        ///&apos;content&apos;:{article_content}
        ///&apos;references&apos;: {article_references}
        ///}
        ///4. Next I will tell you how to find the {article_identifier} and how to create the {article_content}  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtractArticlePromptTemplate {
            get {
                return ResourceManager.GetString("ExtractArticlePromptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an AI language model. Your task is to formulate closed-ended questions (yes/no or specific factual questions) from a given text in Spanish. Follow these guidelines:
        ///1. The text will be enclosed within the next XML tags which contain the article, the law and the year.
        ///  &lt;text&gt;
        ///    &lt;article&gt;&lt;/article&gt;
        ///    &lt;law&gt;&lt;/law&gt;
        ///    &lt;year&gt;&lt;/year&gt;
        ///  &lt;/text&gt;
        ///2. Develop closed-ended questions that have specific, concise answers derived directly from the text.
        ///3. Per each question, provide the response.
        ///4. I [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPromptClosedEndQuestionTemplate {
            get {
                return ResourceManager.GetString("SystemPromptClosedEndQuestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an AI model trained to extract key data from texts in Spanish. Follow these guidelines:
        ///1. The text will be enclosed within the next XML tags which contain the article, the law, and the year:
        ///  &lt;text&gt;
        ///    &lt;article&gt;&lt;/article&gt;
        ///    &lt;law&gt;&lt;/law&gt;
        ///    &lt;year&gt;&lt;/year&gt;
        ///  &lt;/text&gt;
        ///2. Identify and extract key terms, definitions, and any relevant numeric data.
        ///3. In each instruction include the law and the year. Example: Query. De acuerdo a la LISR 2024. ...
        ///4. Return the results in JSON format with the f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPromptInformationExtractionTemplate {
            get {
                return ResourceManager.GetString("SystemPromptInformationExtractionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an AI language model. Given a text in Spanish, generate open-ended questions and the responses. The questions can be answered using the information within the text. Here are your instructions:
        ///1. The text will be enclosed within the next XML tags which contain the article, the law and the year.
        ///  &lt;text&gt;
        ///    &lt;article&gt;&lt;/article&gt;
        ///    &lt;law&gt;&lt;/law&gt;
        ///    &lt;year&gt;&lt;/year&gt;
        ///  &lt;/text&gt;
        ///2. Create insightful, open-ended questions that require deductive reasoning or interpretation of the text.
        ///3. Per each ques [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPromptOpenEndQuestionTemplate {
            get {
                return ResourceManager.GetString("SystemPromptOpenEndQuestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are an AI language model tasked with generating questions about the relationships and references within a legal text in Spanish. Follow these instructions to create the questions:
        ///1. The text will be enclosed within the next XML tags which contain the article, the law, and the year:
        ///  &lt;text&gt;
        ///    &lt;article&gt;&lt;/article&gt;
        ///    &lt;law&gt;&lt;/law&gt;
        ///    &lt;year&gt;&lt;/year&gt;
        ///  &lt;/text&gt;
        ///2. Focus on identifying any mentions of other legal articles, laws, regulations, or references to the Diario Oficial de la Federación (DOF)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPromptReferencesExtractionTemplate {
            get {
                return ResourceManager.GetString("SystemPromptReferencesExtractionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As an AI, you are to summarize texts in Spanish. Follow these guidelines to ensure a comprehensive summary:
        ///1. The text will be enclosed within the next XML tags which contain the article, the law, and the year:
        ///  &lt;text&gt;
        ///    &lt;article&gt;&lt;/article&gt;
        ///    &lt;law&gt;&lt;/law&gt;
        ///    &lt;year&gt;&lt;/year&gt;
        ///  &lt;/text&gt;
        ///2. Create a concise summary capturing the main ideas and key details.
        ///3. Return the results in JSON format with the following structure (example):
        ///{
        ///  &apos;success&apos;: {true|false},
        ///  &apos;instructions&apos;: [{
        ///    &apos;instructi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SystemPromptSummarizationTemplate {
            get {
                return ResourceManager.GetString("SystemPromptSummarizationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text&gt;&lt;article&gt;{article}&lt;/article&gt;&lt;law&gt;{law}&lt;/law&gt;&lt;year&gt;{year}&lt;/year&gt;&lt;/text&gt;.
        /// </summary>
        internal static string UserPromptClosedEndQuestionTemplate {
            get {
                return ResourceManager.GetString("UserPromptClosedEndQuestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text&gt;&lt;article&gt;{article}&lt;/article&gt;&lt;law&gt;{law}&lt;/law&gt;&lt;year&gt;{year}&lt;/year&gt;&lt;/text&gt;.
        /// </summary>
        internal static string UserPromptInformationExtractionTemplate {
            get {
                return ResourceManager.GetString("UserPromptInformationExtractionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text&gt;&lt;article&gt;{article}&lt;/article&gt;&lt;law&gt;{law}&lt;/law&gt;&lt;year&gt;{year}&lt;/year&gt;&lt;/text&gt;.
        /// </summary>
        internal static string UserPromptOpenEndQuestionTemplate {
            get {
                return ResourceManager.GetString("UserPromptOpenEndQuestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text&gt;&lt;article&gt;{article}&lt;/article&gt;&lt;law&gt;{law}&lt;/law&gt;&lt;year&gt;{year}&lt;/year&gt;&lt;/text&gt;.
        /// </summary>
        internal static string UserPromptReferencesExtractionTemplate {
            get {
                return ResourceManager.GetString("UserPromptReferencesExtractionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;text&gt;&lt;article&gt;{article}&lt;/article&gt;&lt;law&gt;{law}&lt;/law&gt;&lt;year&gt;{year}&lt;/year&gt;&lt;/text&gt;.
        /// </summary>
        internal static string UserPromptSummarizationTemplate {
            get {
                return ResourceManager.GetString("UserPromptSummarizationTemplate", resourceCulture);
            }
        }
    }
}
